### ISSUE TITLE
DocxParser: input docx is not completely closed after parsed 

### ISSUE THREAD

**Issue by tanyunshi** [CenterForOpenScience/pydocx#104]
The docx file is not completely closed/released  after parsed by DocxParser. As a result, we cannot delete the docx after being parsed.

For example, the following code gives exception as the file test.docx cannot be deleted as it's used by other process.

    infile = os.path.join(os.path.dirname(__file__), 'docx/test.docx')
    parser = Docx2Html(path=infile)
    print(parser.parsed)
    shutil.rmtree(os.path.join(os.path.dirname(__file__), 'docx'))

I think after the docx is parsed, we should close le ZipExtFile extracted from the zipfile in order to release the docx, for example in DocxParse.py:

    @property
    def parsed(self):
        if not self._parsed:
            self._load()
          
        document_streams = self.document.package.streams
        for ref in document_streams.keys():
             document_streams[ref].close()
       
        return self._parsed

**Comment by kylegibson** [comment]
Have you had a chance to test this out on the current master version of pydocx?

**Comment by tanyunshi** [comment]
@kylegibson, I tested this and it's good. I would like to write a test case but I am not sure how to test if the file is released: I dont think I have the right to create/delete a file in a test(?).

I will close this issue. Thank you very much. :)
