### ISSUE TITLE
Handle unicode characters

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/pydocx#109]
Steps
--------
1. Go to https://osf.io/7dybc/
2. Go to the second line of the content

Expected
-------------
Name would appear as Belén Fernández

Actual
---------
Name appears as Beln Fernndez

I imagine there are a bunch of UTF-8/Unicode characters that aren't being handled properly. In a pinch, they could be converted to ASCII, but much better would be to just pass them through as Unicode.

**Comment by kylegibson** [comment]
Hi Brian,

Thanks for the issue report! In a few days I will be refocusing my development efforts back onto pydocx, and I'll be able to take a look at fixing this issue then. Depending on my schedule, I might be able to get this fixed sometime next week. 

-Kyle

**Comment by brianjgeiger** [comment]
That would be fantastic, thank you very much!

**Comment by kylegibson** [comment]
Hi Brian,

Could you provide a link to the original docx file that was used to generate that HTML? Thanks.

-Kyle

**Comment by brianjgeiger** [comment]
Hi, Kyle,

There should be a green download button on the right-hand side of the screen that will get you the original.

**Comment by kylegibson** [comment]
Yeah, I found that now. Thanks!

**Comment by brianjgeiger** [comment]
:+1:  You're welcome.

**Comment by kylegibson** [comment]
Could you also tell me what version of pydocx you are using?

**Comment by brianjgeiger** [comment]
Sure. Let's see… Oh, I see. Okay, we are currently using a fork located at <https://github.com/mfraezz/pydocx>. @mfraezz is going to bring that up to date with the current version and submit a PR detailing what was changed.

**Comment by mfraezz** [comment]
Submitted PR for my branch. Changes minimal: silencing logging for the OSF and getting HTML returned without a header/footer.
See: https://github.com/CenterForOpenScience/pydocx/pull/110

**Comment by JeffSpies** [comment]
@mfraezz I haven't looked at the PR, but keep in mind that pydocx is a
general purpose library first. Anything specifically for the OSF, should be
done on our side or via generic options of the pydocx library.

**Comment by mfraezz** [comment]
@JeffSpies The only two changes I made should increase the usability of PyDocX as a third-party library in general, I don't think there's anything specific to the OSF. Libraries shouldn't call `logger.basicConfig()`, as this adds a loghandler in addition to any the end-user would already be running. The other change adds a property that allows for rendered html to be embedded without requiring the overhead of stripping headers/footers (e.g. if it's going into a page that already has them). But you're right, I'll change the name of the PR

**Comment by kylegibson** [comment]
@brianjgeiger 

Could you post the code you are using to generate the HTML output from that document?

**Comment by kylegibson** [comment]
Also, can you confirm what version of python you are using?

**Comment by brianjgeiger** [comment]
We are using Python 2.7.6. 

@mfraezz Do you have ready access to the which code is being used to generate the HTML output?

**Comment by mfraezz** [comment]
Yes, it's [here](https://github.com/CenterForOpenScience/modular-file-renderer/blob/dev/mfr/ext/docx/render.py)

@brianjgeiger Your error is probably due the `.encode('ascii', 'ignore')`, actually

**Comment by kylegibson** [comment]
You should be able to change that to `.encode('utf-8')`.

**Comment by brianjgeiger** [comment]
That sounds very likely. I’ll give that a go, and if that fixes it, close out this issue.

**Comment by winhamwr** [comment]
Does #111 have any effect, here?

**Comment by kylegibson** [comment]
I don't suspect it will

**Comment by mfraezz** [comment]
It shouldn't. Stepping through where it's happening in our code, PyDocX is converting everything properly. That `.encode` was left over from when similar files would generate a UnicodeDecodeError, but I can't reproduce that anymore. This issue can be closed.

**Comment by brianjgeiger** [comment]
Thank you for the help on this; I'll keep a closer eye on our side of the chain if we run into any further issues.
