### ISSUE TITLE
Resize images to an appropriate size for the document

### ISSUE THREAD

**Issue by jhubert** [CenterForOpenScience/pydocx#159]
I'm dealing with a number of word documents that have a thumbnail of an image in them, but where the thumbnail is actually just a full-size image visually scaled down.

When PyDocX processes the images, it keeps the image file the same size and uses visual rules to show the image in the intended size.

Do you have any suggestions for how I would set it up to resize the actual image file so that the file size isn't so large?

**Comment by winhamwr** [comment]
We actually implemented something like this in a custom attachment handler.
If I don't post it Monday, please bump this.

-Wes

**Comment by jhubert** [comment]
Awesome. Thanks!

**Comment by winhamwr** [comment]
Hi Jeremy,

Here is a gist for a [resizing pydocx image handler](https://gist.github.com/winhamwr/9dbf16a5a73759e35c43). It's copy/pasted from various parts of our code base, but should include most of the necessary things. It uses `PIL` to do resizing, but is smart about when to resize. It also converts some nasty bitmap formats (bmp, tiff) to compressed formats and handles base64-encoded images.

We would really appreciate it if you could turn this into a mixin in the vein of the [FakedSuperscriptAndSubscriptExportMixin](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/export/mixins/faked_superscript_and_subscript.py#L11) that we could add to the project and then maintain. I'm sure you and I aren't the only ones that would like to solve this problem and it makes sense for it to live out in the open so we can be sure and maintain a working version.

Thanks
-Wes

**Comment by jhubert** [comment]
That's great. Thanks for sharing. I'll take a crack at turning it into a Mixin. I'm not much of a python developer, but I should be able to figure it out. Nothing a code review or two can't fix. :)

**Comment by jhubert** [comment]
@winhamwr Well, this was over my head as far as Python goes. I just didn't end up having the time to sit down and learn everything to implement this properly with tests in Python. I ended up hiring someone to help, and I've submitted the pull-request for review. Thanks again for sharing the original code. Feedback appreciated.

**Comment by winhamwr** [comment]
Hello Jeremy,

> I ended up hiring someone to help, and I've submitted the pull-request for review. Thanks again for sharing the original code. Feedback appreciated.

Thanks so much for sharing the code. Are you using that pull-request in production somewhere?

Hopefully @kylegibson or @jlward can take a closer look at it today. From my quick scan, we need to fix requirements so that the tests pass, but the code looks very similar and the unit tests look great. It would be excellent to get this merged in soon.

-Wes

**Comment by jhubert** [comment]
I'm not using it in production yet. Planning on deploying it today. I've tested it with a number of docx files so far and it seems to perform quite well.

**Comment by jhubert** [comment]
@winhamwr Just as an update, this has been extracted into a standalone plugin: https://github.com/jhubert/pydocx-resize-images

It's been used in production for the last 3 months and it's working great.
