### ISSUE TITLE
Images are not rotated when converting to html

### ISSUE THREAD

**Issue by botzill** [CenterForOpenScience/pydocx#194]
Hi. 

I'm not sure if image rotation is even supported. I'm posting the issue here to find out if it's supported and if there is a way to fix/implement this. 

Here is a test .docx file: https://www.dropbox.com/s/p3rw1wpqp5sywj4/Image%20Should%20Be%20Rotated.docx?dl=0.

In docx file:

<img width="777" alt="screen shot 2015-11-17 at 12 50 24 pm" src="https://cloud.githubusercontent.com/assets/4686040/11209478/eb3c79f2-8d29-11e5-9370-31d68cedd131.png">

After html convert:

<img width="642" alt="screen shot 2015-11-17 at 12 50 49 pm" src="https://cloud.githubusercontent.com/assets/4686040/11209492/fc25ae78-8d29-11e5-867d-dfe52e33b783.png">

Thx.

**Comment by winhamwr** [comment]
Hello Chirica,

Thanks for filing an issue! It looks like we don't currently support this, but we would certainly like to do so.

It looks we we could add an inline css style to the image of `transform: rotate(90deg);` to get the proper effect. Do you have any interest in adding support for this via a Pull Request? We'd be happy to provide guidance.

Thanks again.
-Wes

**Comment by botzill** [comment]
Hi Wes,

I would like to contribute with this feature. Please give me some guidance with some key points:

- How can we detect that an image is rotated?
- Where can I add that CSS entry?

Thx.

**Comment by winhamwr** [comment]
Hi Chirica,

Some items that might be helpful:

* General [development docs](https://pydocx.readthedocs.org/en/latest/development.html)
* The easiest way to start would be to add a testcase using a stripped-down version of the .docx file you provided. [here](https://github.com/swiperthefox/pydocx/commit/e743123f7397af35f5fca5b35210e7def6152e1a) is a commit where someone did that. Basically, add your .docx to e.g. `tests/fixtures/rotated_image.docx` and the HTML you think should be produced (it can be blank to start) to e.g. `tests/fixtures/rotated_image.html` and then add `rotated_image` to the `cases` attribute of `tests/export/test_docx.py:ConvertDocxToHtmlTestCase`. 
* [here](https://github.com/CenterForOpenScience/pydocx/blob/master/tests/openxml/vml/test_shape.py) are some tests on the `shape` element, which seems to be what you're looking for.
* I think you're looking at either a [shape element](http://www.datypic.com/sc/ooxml/e-v_shape.html) or an [image element](http://www.datypic.com/sc/ooxml/e-v_image.html), but I'm not sure. I think there might also be a diagram type? You'll want to examine the XML of your example .docx and locate the element that represents that image. That will point you to the right place in the specification, and then you can find the parser for that element to see what needs to be changed.

If the element you're dealing with is a shape, you'll look at the [shape parser](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/vml/shape.py). Then you'll update either [export_vml_image_data](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/export/html.py#L648) or [export_drawing](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/export/html.py#L585).

I hope this is at least a pointer in the right direction. At the very least, getting a failing testcase with an example document will be a big help.

Thanks
-Wes

**Comment by kylegibson** [comment]
Hi Chirica,

I examined the docx you shared. The rotation is defined in `rot` attribute on the `xfrm` XML tag, which is represented by the [Transform2d](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/drawing/transform_2d.py) class. 

The full hierarchy is: [p](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/wordprocessing/paragraph.py) > [r](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/wordprocessing/run.py) > [drawing](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/wordprocessing/drawing.py) > [anchor](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/drawing/wordprocessing/anchor.py) > [graphic](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/drawing/graphic.py) > [graphicData](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/drawing/graphic_data.py) > [pic](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/drawing/pictures/picture.py) > [spPr](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/drawing/pictures/shape_properties.py) > [xfrm](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/drawing/transform_2d.py). To view this yourself, extract the docx and open `word/document.xml`. 

More details about `Transform2d` is available at [MSDN](https://msdn.microsoft.com/en-us/library/documentformat.openxml.drawing.transform2d%28v=office.14%29.aspx). For `xfrm` you can read §20.4.2.43 of [ECMA 376](http://www.ecma-international.org/publications/standards/Ecma-376.htm).

What you need to do is add a handler for the `rot` attribute to the `Transform2d` class. The data type used for this attribute is defined in §20.1.10.3 as `ST_Angle`:

> This simple type represents an angle in 60,000ths of a degree. Positive angles are clockwise (i.e., towards the positive y axis); negative angles are counter-clockwise (i.e., towards the negative y axis).

For example, the docx you shared has a `rot` value of 5400000. Divide this number by 60000 to get the angle of rotation, which is 90.

Then, [export_drawing](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/export/html.py#L585) can check to see if the image has been rotated and output the necessary markup if it has.

Hope this helps,

-Kyle

**Comment by botzill** [comment]
OK, I submitted a  pull request to this feature, please check it #198

**Comment by winhamwr** [comment]
Fixed via #198 

Thanks so much for the PR, Chirica! We'll also get you added to the AUTHORS file.

-Wes

**Comment by botzill** [comment]
My pleasure. Thx for all the instructions and tips that you provided. Keep the great work.
