### ISSUE TITLE
Document pydocx-resize-images plugin

### ISSUE THREAD

**Issue by winhamwr** [CenterForOpenScience/pydocx#195]
Our documentation should include a resources section that promotes and links to [pydocx-resize-images](https://github.com/jhubert/pydocx-resize-images).

**Comment by winhamwr** [comment]
Related to #159

**Comment by jhubert** [comment]
@winhamwr Agree. Also, happy to roll the code from pydocx-resize-images into this project. I only released it as a plugin so that I wasn't held back by the review / release cycle.

The https://github.com/jhubert/pydocx-s3-images makes more sense as a plugin though. 👯

**Comment by jhubert** [comment]
@winhamwr docs have been merged in. Want to close this issue? 😄

**Comment by winhamwr** [comment]
Thanks for the reminder! Hooray docs.
