### ISSUE TITLE
一个表格内的某个单元格嵌套了一个表格，这怎么能读到内部的东西呢？ 

### ISSUE THREAD

**Issue by 522247020** [CenterForOpenScience/pydocx#254]
![1](https://user-images.githubusercontent.com/38172233/59180154-c0f2be80-8b96-11e9-863e-4a5e7fa10226.png)

**Comment by 522247020** [comment]
谷歌找不到的，官方文档看不懂。电报也没人回复。。
不知怎么把单元格当对象在传到表格函数中。

**Comment by jlward** [comment]
https://github.com/mikemaccana/python-docx
